export const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Approval inbox</title><link rel="stylesheet" href="/assets/inbox.css"><script src="/assets/inbox.js" defer></script></head>
<body><main><h1>Approval inbox</h1><p id="status" role="status">Loading availability…</p>
<p>Local access only. Decisions require exact attempt binding and remain unavailable.</p>
<nav aria-label="Request views"><button id="pending" aria-pressed="true">Pending</button><button id="history" aria-pressed="false">History</button><button id="refresh">Refresh</button></nav>
<ul id="requests" aria-label="Requests"></ul><button id="more" hidden>Load more</button>
<section id="detail" aria-label="Request details" hidden><h2>Details</h2><dl id="fields"></dl><p>Exact attempt binding unavailable (legacy_unbound).</p><button disabled>Approve this operation</button><button disabled>Reject</button></section>
</main></body></html>`;

export const css = `:root{font-family:system-ui,sans-serif;color:#252525;background:#fff;letter-spacing:0}*{box-sizing:border-box}body{margin:0}main{max-width:960px;margin:auto;padding:20px}h1{font-size:24px}p,dd,button{overflow-wrap:anywhere}nav{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}button{font:inherit;min-height:44px;padding:8px 12px;border:1px solid #777;border-radius:6px;background:#fff;color:inherit;cursor:pointer}button:focus-visible{outline:3px solid #226849;outline-offset:3px}button[aria-pressed=true]{background:#e8f1ec;border-color:#226849}button:disabled{color:#666;background:#eee;cursor:not-allowed}ul{padding:0;list-style:none}li{border-bottom:1px solid #ccc;padding:12px 0}li button{text-align:left;width:100%}section{margin-top:24px;border-top:1px solid #ccc}dl{display:grid;grid-template-columns:minmax(80px,140px) minmax(0,1fr);gap:10px}dt{font-weight:600}dd{margin:0;white-space:pre-wrap}#status{padding:12px;border-left:3px solid #927020;background:#faf7ef}[hidden]{display:none!important}@media(max-width:400px){main{padding:12px}dl{grid-template-columns:1fr;gap:6px}dd{margin-bottom:10px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}`;

export const js = `'use strict';
const el=id=>document.getElementById(id);
let view='pending',cursor=null,busy=false,generation=0;
async function get(path){const r=await fetch(path,{credentials:'same-origin',cache:'no-store'});if(!r.ok){throw new Error(r.status===401?'Authentication required.':r.status===503?'Inbox unavailable. Authentication or source verification is required.':'Request unavailable.');}return r.json();}
function field(name,value){const term=document.createElement('dt'),description=document.createElement('dd');term.textContent=name;description.textContent=typeof value==='string'&&value?value:'Unknown';el('fields').append(term,description);}
async function detail(id){const ticket=generation;el('detail').hidden=true;try{const row=await get('/api/requests/'+encodeURIComponent(id)+'?view='+view);if(ticket!==generation)return;el('fields').replaceChildren();field('Request',row.id);field('Question',row.question);field('Worker',row.subjectSid);field('Task',row.task);field('Purpose',row.purpose);field('Scope',row.scope);field('State',row.state);field('Created',row.createdAt);field('Decision',row.decision);el('detail').hidden=false;}catch(e){if(ticket===generation)el('status').textContent=e.message;}}
async function load(append=false){if(busy)return;busy=true;const ticket=++generation;el('refresh').disabled=true;el('more').disabled=true;if(!append){el('requests').replaceChildren();el('detail').hidden=true;cursor=null;}el('status').textContent='Loading…';try{const data=await get('/api/requests?view='+view+'&limit=25'+(append&&cursor?'&cursor='+encodeURIComponent(cursor):''));if(ticket!==generation)return;for(const row of data.items){const li=document.createElement('li'),button=document.createElement('button');button.textContent=row.id+' — '+row.question;button.addEventListener('click',()=>detail(row.id));li.append(button);el('requests').append(li);}cursor=data.nextCursor;el('more').hidden=!cursor;el('status').textContent=data.warnings.length?'Some source records are corrupt or unavailable. Results may be incomplete.':el('requests').children.length?'Read-only requests. Decisions disabled.':'No requests.';}catch(e){el('status').textContent=e.message;el('more').hidden=true;}finally{busy=false;el('refresh').disabled=false;el('more').disabled=false;}}
for(const name of ['pending','history'])el(name).addEventListener('click',()=>{if(busy)return;view=name;el('pending').setAttribute('aria-pressed',String(view==='pending'));el('history').setAttribute('aria-pressed',String(view==='history'));load();});
el('refresh').addEventListener('click',()=>load());el('more').addEventListener('click',()=>load(true));
async function init(){try{const c=await get('/api/capabilities');if(c.auth.state==='ready')await load();else el('status').textContent='Setup unavailable: '+c.auth.reason+'. A verified authentication adapter and trusted localhost TLS are required.';}catch(e){el('status').textContent=e.message;}}
init();`;
